[package]
name = "zk-embed"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
authors = ["eK <team@nonos.systems>"]

# Exclude from parent workspace
[workspace]

[dependencies]
blake3 = "1"
hex = "0.4"
clap = { version = "4.5", features = ["derive"] }

ark-std = { version = "0.4", default-features = true }
ark-ff = { version = "0.4", default-features = true }
ark-serialize = { version = "0.4", default-features = true }
ark-bls12-381 = { version = "0.4", default-features = true, features = ["curve"] }
ark-groth16 = { version = "0.4", default-features = true }
