[build]
target = "x86_64-nonos.json"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-nonos]
rustflags = [
  "-C", "force-frame-pointers=yes",
]

# Platform's are defined in the Makefile for portability
# Use `make run` instead of `cargo run` for QEMU testing
